// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: championban.proto

#ifndef PROTOBUF_championban_2eproto__INCLUDED
#define PROTOBUF_championban_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace guru {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_championban_2eproto();
void protobuf_AssignDesc_championban_2eproto();
void protobuf_ShutdownFile_championban_2eproto();

class ChampionBan;

// ===================================================================

class ChampionBan : public ::google::protobuf::Message {
 public:
  ChampionBan();
  virtual ~ChampionBan();
  
  ChampionBan(const ChampionBan& from);
  
  inline ChampionBan& operator=(const ChampionBan& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChampionBan& default_instance();
  
  void Swap(ChampionBan* other);
  
  // implements Message ----------------------------------------------
  
  ChampionBan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChampionBan& from);
  void MergeFrom(const ChampionBan& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 championId = 1;
  inline bool has_championid() const;
  inline void clear_championid();
  static const int kChampionIdFieldNumber = 1;
  inline ::google::protobuf::uint32 championid() const;
  inline void set_championid(::google::protobuf::uint32 value);
  
  // required bool selfTeam = 2;
  inline bool has_selfteam() const;
  inline void clear_selfteam();
  static const int kSelfTeamFieldNumber = 2;
  inline bool selfteam() const;
  inline void set_selfteam(bool value);
  
  // @@protoc_insertion_point(class_scope:guru.ChampionBan)
 private:
  inline void set_has_championid();
  inline void clear_has_championid();
  inline void set_has_selfteam();
  inline void clear_has_selfteam();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 championid_;
  bool selfteam_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_championban_2eproto();
  friend void protobuf_AssignDesc_championban_2eproto();
  friend void protobuf_ShutdownFile_championban_2eproto();
  
  void InitAsDefaultInstance();
  static ChampionBan* default_instance_;
};
// ===================================================================


// ===================================================================

// ChampionBan

// required uint32 championId = 1;
inline bool ChampionBan::has_championid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChampionBan::set_has_championid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChampionBan::clear_has_championid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChampionBan::clear_championid() {
  championid_ = 0u;
  clear_has_championid();
}
inline ::google::protobuf::uint32 ChampionBan::championid() const {
  return championid_;
}
inline void ChampionBan::set_championid(::google::protobuf::uint32 value) {
  set_has_championid();
  championid_ = value;
}

// required bool selfTeam = 2;
inline bool ChampionBan::has_selfteam() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChampionBan::set_has_selfteam() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChampionBan::clear_has_selfteam() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChampionBan::clear_selfteam() {
  selfteam_ = false;
  clear_has_selfteam();
}
inline bool ChampionBan::selfteam() const {
  return selfteam_;
}
inline void ChampionBan::set_selfteam(bool value) {
  set_has_selfteam();
  selfteam_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_championban_2eproto__INCLUDED
