// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lockparticipant.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace guru {

namespace {

const ::google::protobuf::Descriptor* LockParticipant_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LockParticipant_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lockparticipant_2eproto() {
  protobuf_AddDesc_lockparticipant_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lockparticipant.proto");
  GOOGLE_CHECK(file != NULL);
  LockParticipant_descriptor_ = file->message_type(0);
  static const int LockParticipant_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LockParticipant, participant_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LockParticipant, championid_),
  };
  LockParticipant_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LockParticipant_descriptor_,
      LockParticipant::default_instance_,
      LockParticipant_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LockParticipant, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LockParticipant, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LockParticipant));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lockparticipant_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LockParticipant_descriptor_, &LockParticipant::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lockparticipant_2eproto() {
  delete LockParticipant::default_instance_;
  delete LockParticipant_reflection_;
}

void protobuf_AddDesc_lockparticipant_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025lockparticipant.proto\022\004guru\":\n\017LockPar"
    "ticipant\022\023\n\013participant\030\001 \002(\r\022\022\n\nchampio"
    "nId\030\002 \001(\r", 89);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lockparticipant.proto", &protobuf_RegisterTypes);
  LockParticipant::default_instance_ = new LockParticipant();
  LockParticipant::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lockparticipant_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lockparticipant_2eproto {
  StaticDescriptorInitializer_lockparticipant_2eproto() {
    protobuf_AddDesc_lockparticipant_2eproto();
  }
} static_descriptor_initializer_lockparticipant_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int LockParticipant::kParticipantFieldNumber;
const int LockParticipant::kChampionIdFieldNumber;
#endif  // !_MSC_VER

LockParticipant::LockParticipant()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LockParticipant::InitAsDefaultInstance() {
}

LockParticipant::LockParticipant(const LockParticipant& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LockParticipant::SharedCtor() {
  _cached_size_ = 0;
  participant_ = 0u;
  championid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LockParticipant::~LockParticipant() {
  SharedDtor();
}

void LockParticipant::SharedDtor() {
  if (this != default_instance_) {
  }
}

void LockParticipant::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LockParticipant::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LockParticipant_descriptor_;
}

const LockParticipant& LockParticipant::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lockparticipant_2eproto();  return *default_instance_;
}

LockParticipant* LockParticipant::default_instance_ = NULL;

LockParticipant* LockParticipant::New() const {
  return new LockParticipant;
}

void LockParticipant::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    participant_ = 0u;
    championid_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LockParticipant::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 participant = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &participant_)));
          set_has_participant();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_championId;
        break;
      }
      
      // optional uint32 championId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_championId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &championid_)));
          set_has_championid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LockParticipant::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 participant = 1;
  if (has_participant()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->participant(), output);
  }
  
  // optional uint32 championId = 2;
  if (has_championid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->championid(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LockParticipant::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 participant = 1;
  if (has_participant()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->participant(), target);
  }
  
  // optional uint32 championId = 2;
  if (has_championid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->championid(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LockParticipant::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 participant = 1;
    if (has_participant()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->participant());
    }
    
    // optional uint32 championId = 2;
    if (has_championid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->championid());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LockParticipant::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LockParticipant* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LockParticipant*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LockParticipant::MergeFrom(const LockParticipant& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_participant()) {
      set_participant(from.participant());
    }
    if (from.has_championid()) {
      set_championid(from.championid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LockParticipant::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LockParticipant::CopyFrom(const LockParticipant& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LockParticipant::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void LockParticipant::Swap(LockParticipant* other) {
  if (other != this) {
    std::swap(participant_, other->participant_);
    std::swap(championid_, other->championid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LockParticipant::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LockParticipant_descriptor_;
  metadata.reflection = LockParticipant_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

// @@protoc_insertion_point(global_scope)
