// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matchupcreated.proto

#ifndef PROTOBUF_matchupcreated_2eproto__INCLUDED
#define PROTOBUF_matchupcreated_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace guru {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_matchupcreated_2eproto();
void protobuf_AssignDesc_matchupcreated_2eproto();
void protobuf_ShutdownFile_matchupcreated_2eproto();

class MatchupCreated;

// ===================================================================

class MatchupCreated : public ::google::protobuf::Message {
 public:
  MatchupCreated();
  virtual ~MatchupCreated();
  
  MatchupCreated(const MatchupCreated& from);
  
  inline MatchupCreated& operator=(const MatchupCreated& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MatchupCreated& default_instance();
  
  void Swap(MatchupCreated* other);
  
  // implements Message ----------------------------------------------
  
  MatchupCreated* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MatchupCreated& from);
  void MergeFrom(const MatchupCreated& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // required string key = 2;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 2;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  
  // @@protoc_insertion_point(class_scope:guru.MatchupCreated)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_key();
  inline void clear_has_key();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* key_;
  ::google::protobuf::uint32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_matchupcreated_2eproto();
  friend void protobuf_AssignDesc_matchupcreated_2eproto();
  friend void protobuf_ShutdownFile_matchupcreated_2eproto();
  
  void InitAsDefaultInstance();
  static MatchupCreated* default_instance_;
};
// ===================================================================


// ===================================================================

// MatchupCreated

// required uint32 id = 1;
inline bool MatchupCreated::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MatchupCreated::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MatchupCreated::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MatchupCreated::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 MatchupCreated::id() const {
  return id_;
}
inline void MatchupCreated::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string key = 2;
inline bool MatchupCreated::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MatchupCreated::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MatchupCreated::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MatchupCreated::clear_key() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& MatchupCreated::key() const {
  return *key_;
}
inline void MatchupCreated::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void MatchupCreated::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void MatchupCreated::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MatchupCreated::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::std::string* MatchupCreated::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_matchupcreated_2eproto__INCLUDED
