// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: participantsquery.proto

#ifndef PROTOBUF_participantsquery_2eproto__INCLUDED
#define PROTOBUF_participantsquery_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace guru {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_participantsquery_2eproto();
void protobuf_AssignDesc_participantsquery_2eproto();
void protobuf_ShutdownFile_participantsquery_2eproto();

class ParticipantsQuery;

// ===================================================================

class ParticipantsQuery : public ::google::protobuf::Message {
 public:
  ParticipantsQuery();
  virtual ~ParticipantsQuery();
  
  ParticipantsQuery(const ParticipantsQuery& from);
  
  inline ParticipantsQuery& operator=(const ParticipantsQuery& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ParticipantsQuery& default_instance();
  
  void Swap(ParticipantsQuery* other);
  
  // implements Message ----------------------------------------------
  
  ParticipantsQuery* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParticipantsQuery& from);
  void MergeFrom(const ParticipantsQuery& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated uint32 participant = 1;
  inline int participant_size() const;
  inline void clear_participant();
  static const int kParticipantFieldNumber = 1;
  inline ::google::protobuf::uint32 participant(int index) const;
  inline void set_participant(int index, ::google::protobuf::uint32 value);
  inline void add_participant(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      participant() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_participant();
  
  // @@protoc_insertion_point(class_scope:guru.ParticipantsQuery)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > participant_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_participantsquery_2eproto();
  friend void protobuf_AssignDesc_participantsquery_2eproto();
  friend void protobuf_ShutdownFile_participantsquery_2eproto();
  
  void InitAsDefaultInstance();
  static ParticipantsQuery* default_instance_;
};
// ===================================================================


// ===================================================================

// ParticipantsQuery

// repeated uint32 participant = 1;
inline int ParticipantsQuery::participant_size() const {
  return participant_.size();
}
inline void ParticipantsQuery::clear_participant() {
  participant_.Clear();
}
inline ::google::protobuf::uint32 ParticipantsQuery::participant(int index) const {
  return participant_.Get(index);
}
inline void ParticipantsQuery::set_participant(int index, ::google::protobuf::uint32 value) {
  participant_.Set(index, value);
}
inline void ParticipantsQuery::add_participant(::google::protobuf::uint32 value) {
  participant_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ParticipantsQuery::participant() const {
  return participant_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ParticipantsQuery::mutable_participant() {
  return &participant_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_participantsquery_2eproto__INCLUDED
