// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: participantstartspicking.proto

#ifndef PROTOBUF_participantstartspicking_2eproto__INCLUDED
#define PROTOBUF_participantstartspicking_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace guru {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_participantstartspicking_2eproto();
void protobuf_AssignDesc_participantstartspicking_2eproto();
void protobuf_ShutdownFile_participantstartspicking_2eproto();

class ParticipantStartsPicking;

// ===================================================================

class ParticipantStartsPicking : public ::google::protobuf::Message {
 public:
  ParticipantStartsPicking();
  virtual ~ParticipantStartsPicking();
  
  ParticipantStartsPicking(const ParticipantStartsPicking& from);
  
  inline ParticipantStartsPicking& operator=(const ParticipantStartsPicking& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ParticipantStartsPicking& default_instance();
  
  void Swap(ParticipantStartsPicking* other);
  
  // implements Message ----------------------------------------------
  
  ParticipantStartsPicking* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParticipantStartsPicking& from);
  void MergeFrom(const ParticipantStartsPicking& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 participant = 1;
  inline bool has_participant() const;
  inline void clear_participant();
  static const int kParticipantFieldNumber = 1;
  inline ::google::protobuf::uint32 participant() const;
  inline void set_participant(::google::protobuf::uint32 value);
  
  // optional fixed64 start = 2;
  inline bool has_start() const;
  inline void clear_start();
  static const int kStartFieldNumber = 2;
  inline ::google::protobuf::uint64 start() const;
  inline void set_start(::google::protobuf::uint64 value);
  
  // optional uint32 timer = 3;
  inline bool has_timer() const;
  inline void clear_timer();
  static const int kTimerFieldNumber = 3;
  inline ::google::protobuf::uint32 timer() const;
  inline void set_timer(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:guru.ParticipantStartsPicking)
 private:
  inline void set_has_participant();
  inline void clear_has_participant();
  inline void set_has_start();
  inline void clear_has_start();
  inline void set_has_timer();
  inline void clear_has_timer();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 start_;
  ::google::protobuf::uint32 participant_;
  ::google::protobuf::uint32 timer_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_participantstartspicking_2eproto();
  friend void protobuf_AssignDesc_participantstartspicking_2eproto();
  friend void protobuf_ShutdownFile_participantstartspicking_2eproto();
  
  void InitAsDefaultInstance();
  static ParticipantStartsPicking* default_instance_;
};
// ===================================================================


// ===================================================================

// ParticipantStartsPicking

// required uint32 participant = 1;
inline bool ParticipantStartsPicking::has_participant() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParticipantStartsPicking::set_has_participant() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParticipantStartsPicking::clear_has_participant() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParticipantStartsPicking::clear_participant() {
  participant_ = 0u;
  clear_has_participant();
}
inline ::google::protobuf::uint32 ParticipantStartsPicking::participant() const {
  return participant_;
}
inline void ParticipantStartsPicking::set_participant(::google::protobuf::uint32 value) {
  set_has_participant();
  participant_ = value;
}

// optional fixed64 start = 2;
inline bool ParticipantStartsPicking::has_start() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParticipantStartsPicking::set_has_start() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParticipantStartsPicking::clear_has_start() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParticipantStartsPicking::clear_start() {
  start_ = GOOGLE_ULONGLONG(0);
  clear_has_start();
}
inline ::google::protobuf::uint64 ParticipantStartsPicking::start() const {
  return start_;
}
inline void ParticipantStartsPicking::set_start(::google::protobuf::uint64 value) {
  set_has_start();
  start_ = value;
}

// optional uint32 timer = 3;
inline bool ParticipantStartsPicking::has_timer() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ParticipantStartsPicking::set_has_timer() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ParticipantStartsPicking::clear_has_timer() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ParticipantStartsPicking::clear_timer() {
  timer_ = 0u;
  clear_has_timer();
}
inline ::google::protobuf::uint32 ParticipantStartsPicking::timer() const {
  return timer_;
}
inline void ParticipantStartsPicking::set_timer(::google::protobuf::uint32 value) {
  set_has_timer();
  timer_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_participantstartspicking_2eproto__INCLUDED
