// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "participantspells.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace guru {

namespace {

const ::google::protobuf::Descriptor* ParticipantSpells_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParticipantSpells_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_participantspells_2eproto() {
  protobuf_AddDesc_participantspells_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "participantspells.proto");
  GOOGLE_CHECK(file != NULL);
  ParticipantSpells_descriptor_ = file->message_type(0);
  static const int ParticipantSpells_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantSpells, participant_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantSpells, spell1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantSpells, spell2_),
  };
  ParticipantSpells_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ParticipantSpells_descriptor_,
      ParticipantSpells::default_instance_,
      ParticipantSpells_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantSpells, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantSpells, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ParticipantSpells));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_participantspells_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ParticipantSpells_descriptor_, &ParticipantSpells::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_participantspells_2eproto() {
  delete ParticipantSpells::default_instance_;
  delete ParticipantSpells_reflection_;
}

void protobuf_AddDesc_participantspells_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027participantspells.proto\022\004guru\"H\n\021Parti"
    "cipantSpells\022\023\n\013participant\030\001 \002(\r\022\016\n\006spe"
    "ll1\030\002 \002(\r\022\016\n\006spell2\030\003 \002(\r", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "participantspells.proto", &protobuf_RegisterTypes);
  ParticipantSpells::default_instance_ = new ParticipantSpells();
  ParticipantSpells::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_participantspells_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_participantspells_2eproto {
  StaticDescriptorInitializer_participantspells_2eproto() {
    protobuf_AddDesc_participantspells_2eproto();
  }
} static_descriptor_initializer_participantspells_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ParticipantSpells::kParticipantFieldNumber;
const int ParticipantSpells::kSpell1FieldNumber;
const int ParticipantSpells::kSpell2FieldNumber;
#endif  // !_MSC_VER

ParticipantSpells::ParticipantSpells()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ParticipantSpells::InitAsDefaultInstance() {
}

ParticipantSpells::ParticipantSpells(const ParticipantSpells& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ParticipantSpells::SharedCtor() {
  _cached_size_ = 0;
  participant_ = 0u;
  spell1_ = 0u;
  spell2_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParticipantSpells::~ParticipantSpells() {
  SharedDtor();
}

void ParticipantSpells::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ParticipantSpells::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParticipantSpells::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParticipantSpells_descriptor_;
}

const ParticipantSpells& ParticipantSpells::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_participantspells_2eproto();  return *default_instance_;
}

ParticipantSpells* ParticipantSpells::default_instance_ = NULL;

ParticipantSpells* ParticipantSpells::New() const {
  return new ParticipantSpells;
}

void ParticipantSpells::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    participant_ = 0u;
    spell1_ = 0u;
    spell2_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ParticipantSpells::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 participant = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &participant_)));
          set_has_participant();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_spell1;
        break;
      }
      
      // required uint32 spell1 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_spell1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &spell1_)));
          set_has_spell1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_spell2;
        break;
      }
      
      // required uint32 spell2 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_spell2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &spell2_)));
          set_has_spell2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ParticipantSpells::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 participant = 1;
  if (has_participant()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->participant(), output);
  }
  
  // required uint32 spell1 = 2;
  if (has_spell1()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->spell1(), output);
  }
  
  // required uint32 spell2 = 3;
  if (has_spell2()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->spell2(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ParticipantSpells::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 participant = 1;
  if (has_participant()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->participant(), target);
  }
  
  // required uint32 spell1 = 2;
  if (has_spell1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->spell1(), target);
  }
  
  // required uint32 spell2 = 3;
  if (has_spell2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->spell2(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ParticipantSpells::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 participant = 1;
    if (has_participant()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->participant());
    }
    
    // required uint32 spell1 = 2;
    if (has_spell1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->spell1());
    }
    
    // required uint32 spell2 = 3;
    if (has_spell2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->spell2());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParticipantSpells::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ParticipantSpells* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ParticipantSpells*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ParticipantSpells::MergeFrom(const ParticipantSpells& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_participant()) {
      set_participant(from.participant());
    }
    if (from.has_spell1()) {
      set_spell1(from.spell1());
    }
    if (from.has_spell2()) {
      set_spell2(from.spell2());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ParticipantSpells::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParticipantSpells::CopyFrom(const ParticipantSpells& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParticipantSpells::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void ParticipantSpells::Swap(ParticipantSpells* other) {
  if (other != this) {
    std::swap(participant_, other->participant_);
    std::swap(spell1_, other->spell1_);
    std::swap(spell2_, other->spell2_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ParticipantSpells::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParticipantSpells_descriptor_;
  metadata.reflection = ParticipantSpells_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

// @@protoc_insertion_point(global_scope)
