// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "participantsquery.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace guru {

namespace {

const ::google::protobuf::Descriptor* ParticipantsQuery_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParticipantsQuery_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_participantsquery_2eproto() {
  protobuf_AddDesc_participantsquery_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "participantsquery.proto");
  GOOGLE_CHECK(file != NULL);
  ParticipantsQuery_descriptor_ = file->message_type(0);
  static const int ParticipantsQuery_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantsQuery, participant_),
  };
  ParticipantsQuery_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ParticipantsQuery_descriptor_,
      ParticipantsQuery::default_instance_,
      ParticipantsQuery_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantsQuery, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantsQuery, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ParticipantsQuery));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_participantsquery_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ParticipantsQuery_descriptor_, &ParticipantsQuery::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_participantsquery_2eproto() {
  delete ParticipantsQuery::default_instance_;
  delete ParticipantsQuery_reflection_;
}

void protobuf_AddDesc_participantsquery_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027participantsquery.proto\022\004guru\"(\n\021Parti"
    "cipantsQuery\022\023\n\013participant\030\001 \003(\r", 73);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "participantsquery.proto", &protobuf_RegisterTypes);
  ParticipantsQuery::default_instance_ = new ParticipantsQuery();
  ParticipantsQuery::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_participantsquery_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_participantsquery_2eproto {
  StaticDescriptorInitializer_participantsquery_2eproto() {
    protobuf_AddDesc_participantsquery_2eproto();
  }
} static_descriptor_initializer_participantsquery_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ParticipantsQuery::kParticipantFieldNumber;
#endif  // !_MSC_VER

ParticipantsQuery::ParticipantsQuery()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ParticipantsQuery::InitAsDefaultInstance() {
}

ParticipantsQuery::ParticipantsQuery(const ParticipantsQuery& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ParticipantsQuery::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParticipantsQuery::~ParticipantsQuery() {
  SharedDtor();
}

void ParticipantsQuery::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ParticipantsQuery::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParticipantsQuery::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParticipantsQuery_descriptor_;
}

const ParticipantsQuery& ParticipantsQuery::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_participantsquery_2eproto();  return *default_instance_;
}

ParticipantsQuery* ParticipantsQuery::default_instance_ = NULL;

ParticipantsQuery* ParticipantsQuery::New() const {
  return new ParticipantsQuery;
}

void ParticipantsQuery::Clear() {
  participant_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ParticipantsQuery::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 participant = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_participant:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 8, input, this->mutable_participant())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_participant())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_participant;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ParticipantsQuery::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated uint32 participant = 1;
  for (int i = 0; i < this->participant_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      1, this->participant(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ParticipantsQuery::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated uint32 participant = 1;
  for (int i = 0; i < this->participant_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(1, this->participant(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ParticipantsQuery::ByteSize() const {
  int total_size = 0;
  
  // repeated uint32 participant = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->participant_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->participant(i));
    }
    total_size += 1 * this->participant_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParticipantsQuery::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ParticipantsQuery* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ParticipantsQuery*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ParticipantsQuery::MergeFrom(const ParticipantsQuery& from) {
  GOOGLE_CHECK_NE(&from, this);
  participant_.MergeFrom(from.participant_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ParticipantsQuery::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParticipantsQuery::CopyFrom(const ParticipantsQuery& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParticipantsQuery::IsInitialized() const {
  
  return true;
}

void ParticipantsQuery::Swap(ParticipantsQuery* other) {
  if (other != this) {
    participant_.Swap(&other->participant_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ParticipantsQuery::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParticipantsQuery_descriptor_;
  metadata.reflection = ParticipantsQuery_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

// @@protoc_insertion_point(global_scope)
