// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "participantstartspicking.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace guru {

namespace {

const ::google::protobuf::Descriptor* ParticipantStartsPicking_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParticipantStartsPicking_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_participantstartspicking_2eproto() {
  protobuf_AddDesc_participantstartspicking_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "participantstartspicking.proto");
  GOOGLE_CHECK(file != NULL);
  ParticipantStartsPicking_descriptor_ = file->message_type(0);
  static const int ParticipantStartsPicking_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantStartsPicking, participant_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantStartsPicking, start_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantStartsPicking, timer_),
  };
  ParticipantStartsPicking_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ParticipantStartsPicking_descriptor_,
      ParticipantStartsPicking::default_instance_,
      ParticipantStartsPicking_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantStartsPicking, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParticipantStartsPicking, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ParticipantStartsPicking));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_participantstartspicking_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ParticipantStartsPicking_descriptor_, &ParticipantStartsPicking::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_participantstartspicking_2eproto() {
  delete ParticipantStartsPicking::default_instance_;
  delete ParticipantStartsPicking_reflection_;
}

void protobuf_AddDesc_participantstartspicking_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036participantstartspicking.proto\022\004guru\"M"
    "\n\030ParticipantStartsPicking\022\023\n\013participan"
    "t\030\001 \002(\r\022\r\n\005start\030\002 \001(\006\022\r\n\005timer\030\003 \001(\r", 117);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "participantstartspicking.proto", &protobuf_RegisterTypes);
  ParticipantStartsPicking::default_instance_ = new ParticipantStartsPicking();
  ParticipantStartsPicking::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_participantstartspicking_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_participantstartspicking_2eproto {
  StaticDescriptorInitializer_participantstartspicking_2eproto() {
    protobuf_AddDesc_participantstartspicking_2eproto();
  }
} static_descriptor_initializer_participantstartspicking_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ParticipantStartsPicking::kParticipantFieldNumber;
const int ParticipantStartsPicking::kStartFieldNumber;
const int ParticipantStartsPicking::kTimerFieldNumber;
#endif  // !_MSC_VER

ParticipantStartsPicking::ParticipantStartsPicking()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ParticipantStartsPicking::InitAsDefaultInstance() {
}

ParticipantStartsPicking::ParticipantStartsPicking(const ParticipantStartsPicking& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ParticipantStartsPicking::SharedCtor() {
  _cached_size_ = 0;
  participant_ = 0u;
  start_ = GOOGLE_ULONGLONG(0);
  timer_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParticipantStartsPicking::~ParticipantStartsPicking() {
  SharedDtor();
}

void ParticipantStartsPicking::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ParticipantStartsPicking::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParticipantStartsPicking::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParticipantStartsPicking_descriptor_;
}

const ParticipantStartsPicking& ParticipantStartsPicking::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_participantstartspicking_2eproto();  return *default_instance_;
}

ParticipantStartsPicking* ParticipantStartsPicking::default_instance_ = NULL;

ParticipantStartsPicking* ParticipantStartsPicking::New() const {
  return new ParticipantStartsPicking;
}

void ParticipantStartsPicking::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    participant_ = 0u;
    start_ = GOOGLE_ULONGLONG(0);
    timer_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ParticipantStartsPicking::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 participant = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &participant_)));
          set_has_participant();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_start;
        break;
      }
      
      // optional fixed64 start = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_start:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &start_)));
          set_has_start();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_timer;
        break;
      }
      
      // optional uint32 timer = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timer:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &timer_)));
          set_has_timer();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ParticipantStartsPicking::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 participant = 1;
  if (has_participant()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->participant(), output);
  }
  
  // optional fixed64 start = 2;
  if (has_start()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(2, this->start(), output);
  }
  
  // optional uint32 timer = 3;
  if (has_timer()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->timer(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ParticipantStartsPicking::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 participant = 1;
  if (has_participant()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->participant(), target);
  }
  
  // optional fixed64 start = 2;
  if (has_start()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(2, this->start(), target);
  }
  
  // optional uint32 timer = 3;
  if (has_timer()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->timer(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ParticipantStartsPicking::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 participant = 1;
    if (has_participant()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->participant());
    }
    
    // optional fixed64 start = 2;
    if (has_start()) {
      total_size += 1 + 8;
    }
    
    // optional uint32 timer = 3;
    if (has_timer()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->timer());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParticipantStartsPicking::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ParticipantStartsPicking* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ParticipantStartsPicking*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ParticipantStartsPicking::MergeFrom(const ParticipantStartsPicking& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_participant()) {
      set_participant(from.participant());
    }
    if (from.has_start()) {
      set_start(from.start());
    }
    if (from.has_timer()) {
      set_timer(from.timer());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ParticipantStartsPicking::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParticipantStartsPicking::CopyFrom(const ParticipantStartsPicking& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParticipantStartsPicking::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void ParticipantStartsPicking::Swap(ParticipantStartsPicking* other) {
  if (other != this) {
    std::swap(participant_, other->participant_);
    std::swap(start_, other->start_);
    std::swap(timer_, other->timer_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ParticipantStartsPicking::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParticipantStartsPicking_descriptor_;
  metadata.reflection = ParticipantStartsPicking_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

// @@protoc_insertion_point(global_scope)
