// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: participantspells.proto

#ifndef PROTOBUF_participantspells_2eproto__INCLUDED
#define PROTOBUF_participantspells_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace guru {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_participantspells_2eproto();
void protobuf_AssignDesc_participantspells_2eproto();
void protobuf_ShutdownFile_participantspells_2eproto();

class ParticipantSpells;

// ===================================================================

class ParticipantSpells : public ::google::protobuf::Message {
 public:
  ParticipantSpells();
  virtual ~ParticipantSpells();
  
  ParticipantSpells(const ParticipantSpells& from);
  
  inline ParticipantSpells& operator=(const ParticipantSpells& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ParticipantSpells& default_instance();
  
  void Swap(ParticipantSpells* other);
  
  // implements Message ----------------------------------------------
  
  ParticipantSpells* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParticipantSpells& from);
  void MergeFrom(const ParticipantSpells& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 participant = 1;
  inline bool has_participant() const;
  inline void clear_participant();
  static const int kParticipantFieldNumber = 1;
  inline ::google::protobuf::uint32 participant() const;
  inline void set_participant(::google::protobuf::uint32 value);
  
  // required uint32 spell1 = 2;
  inline bool has_spell1() const;
  inline void clear_spell1();
  static const int kSpell1FieldNumber = 2;
  inline ::google::protobuf::uint32 spell1() const;
  inline void set_spell1(::google::protobuf::uint32 value);
  
  // required uint32 spell2 = 3;
  inline bool has_spell2() const;
  inline void clear_spell2();
  static const int kSpell2FieldNumber = 3;
  inline ::google::protobuf::uint32 spell2() const;
  inline void set_spell2(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:guru.ParticipantSpells)
 private:
  inline void set_has_participant();
  inline void clear_has_participant();
  inline void set_has_spell1();
  inline void clear_has_spell1();
  inline void set_has_spell2();
  inline void clear_has_spell2();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 participant_;
  ::google::protobuf::uint32 spell1_;
  ::google::protobuf::uint32 spell2_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_participantspells_2eproto();
  friend void protobuf_AssignDesc_participantspells_2eproto();
  friend void protobuf_ShutdownFile_participantspells_2eproto();
  
  void InitAsDefaultInstance();
  static ParticipantSpells* default_instance_;
};
// ===================================================================


// ===================================================================

// ParticipantSpells

// required uint32 participant = 1;
inline bool ParticipantSpells::has_participant() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParticipantSpells::set_has_participant() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParticipantSpells::clear_has_participant() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParticipantSpells::clear_participant() {
  participant_ = 0u;
  clear_has_participant();
}
inline ::google::protobuf::uint32 ParticipantSpells::participant() const {
  return participant_;
}
inline void ParticipantSpells::set_participant(::google::protobuf::uint32 value) {
  set_has_participant();
  participant_ = value;
}

// required uint32 spell1 = 2;
inline bool ParticipantSpells::has_spell1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParticipantSpells::set_has_spell1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParticipantSpells::clear_has_spell1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParticipantSpells::clear_spell1() {
  spell1_ = 0u;
  clear_has_spell1();
}
inline ::google::protobuf::uint32 ParticipantSpells::spell1() const {
  return spell1_;
}
inline void ParticipantSpells::set_spell1(::google::protobuf::uint32 value) {
  set_has_spell1();
  spell1_ = value;
}

// required uint32 spell2 = 3;
inline bool ParticipantSpells::has_spell2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ParticipantSpells::set_has_spell2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ParticipantSpells::clear_has_spell2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ParticipantSpells::clear_spell2() {
  spell2_ = 0u;
  clear_has_spell2();
}
inline ::google::protobuf::uint32 ParticipantSpells::spell2() const {
  return spell2_;
}
inline void ParticipantSpells::set_spell2(::google::protobuf::uint32 value) {
  set_has_spell2();
  spell2_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace guru

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_participantspells_2eproto__INCLUDED
